/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as DemoAiChatRouteImport } from './routes/demo/ai-chat'
import { Route as DemoAiImageRouteImport } from './routes/demo/ai-image'
import { Route as DemoAiStructuredRouteImport } from './routes/demo/ai-structured'
import { Route as DemoStoreRouteImport } from './routes/demo/store'
import { Route as DemoRouterSnippetIdRouteImport } from './routes/demo/router/$snippetId'
import { Route as DemoApiAiChatRouteImport } from './routes/demo/api.ai.chat'
import { Route as DemoApiAiCopykitRouteImport } from './routes/demo/api.ai.copykit'
import { Route as DemoApiAiImageRouteImport } from './routes/demo/api.ai.image'
import { Route as DemoApiAiStructuredRouteImport } from './routes/demo/api.ai.structured'
import { Route as DemoApiAiTranscriptionRouteImport } from './routes/demo/api.ai.transcription'
import { Route as DemoApiAiTtsRouteImport } from './routes/demo/api.ai.tts'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoAiChatRoute = DemoAiChatRouteImport.update({
  id: '/demo/ai-chat',
  path: '/demo/ai-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoAiImageRoute = DemoAiImageRouteImport.update({
  id: '/demo/ai-image',
  path: '/demo/ai-image',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoAiStructuredRoute = DemoAiStructuredRouteImport.update({
  id: '/demo/ai-structured',
  path: '/demo/ai-structured',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStoreRoute = DemoStoreRouteImport.update({
  id: '/demo/store',
  path: '/demo/store',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRouterSnippetIdRoute = DemoRouterSnippetIdRouteImport.update({
  id: '/demo/router/$snippetId',
  path: '/demo/router/$snippetId',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiAiChatRoute = DemoApiAiChatRouteImport.update({
  id: '/demo/api/ai/chat',
  path: '/demo/api/ai/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiAiCopykitRoute = DemoApiAiCopykitRouteImport.update({
  id: '/demo/api/ai/copykit',
  path: '/demo/api/ai/copykit',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiAiImageRoute = DemoApiAiImageRouteImport.update({
  id: '/demo/api/ai/image',
  path: '/demo/api/ai/image',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiAiStructuredRoute = DemoApiAiStructuredRouteImport.update({
  id: '/demo/api/ai/structured',
  path: '/demo/api/ai/structured',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiAiTranscriptionRoute = DemoApiAiTranscriptionRouteImport.update({
  id: '/demo/api/ai/transcription',
  path: '/demo/api/ai/transcription',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiAiTtsRoute = DemoApiAiTtsRouteImport.update({
  id: '/demo/api/ai/tts',
  path: '/demo/api/ai/tts',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/studio': typeof StudioRoute
  '/demo/ai-chat': typeof DemoAiChatRoute
  '/demo/ai-image': typeof DemoAiImageRoute
  '/demo/ai-structured': typeof DemoAiStructuredRoute
  '/demo/store': typeof DemoStoreRoute
  '/demo/router/$snippetId': typeof DemoRouterSnippetIdRoute
  '/demo/api/ai/chat': typeof DemoApiAiChatRoute
  '/demo/api/ai/copykit': typeof DemoApiAiCopykitRoute
  '/demo/api/ai/image': typeof DemoApiAiImageRoute
  '/demo/api/ai/structured': typeof DemoApiAiStructuredRoute
  '/demo/api/ai/transcription': typeof DemoApiAiTranscriptionRoute
  '/demo/api/ai/tts': typeof DemoApiAiTtsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/studio': typeof StudioRoute
  '/demo/ai-chat': typeof DemoAiChatRoute
  '/demo/ai-image': typeof DemoAiImageRoute
  '/demo/ai-structured': typeof DemoAiStructuredRoute
  '/demo/store': typeof DemoStoreRoute
  '/demo/router/$snippetId': typeof DemoRouterSnippetIdRoute
  '/demo/api/ai/chat': typeof DemoApiAiChatRoute
  '/demo/api/ai/copykit': typeof DemoApiAiCopykitRoute
  '/demo/api/ai/image': typeof DemoApiAiImageRoute
  '/demo/api/ai/structured': typeof DemoApiAiStructuredRoute
  '/demo/api/ai/transcription': typeof DemoApiAiTranscriptionRoute
  '/demo/api/ai/tts': typeof DemoApiAiTtsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/studio': typeof StudioRoute
  '/demo/ai-chat': typeof DemoAiChatRoute
  '/demo/ai-image': typeof DemoAiImageRoute
  '/demo/ai-structured': typeof DemoAiStructuredRoute
  '/demo/store': typeof DemoStoreRoute
  '/demo/router/$snippetId': typeof DemoRouterSnippetIdRoute
  '/demo/api/ai/chat': typeof DemoApiAiChatRoute
  '/demo/api/ai/copykit': typeof DemoApiAiCopykitRoute
  '/demo/api/ai/image': typeof DemoApiAiImageRoute
  '/demo/api/ai/structured': typeof DemoApiAiStructuredRoute
  '/demo/api/ai/transcription': typeof DemoApiAiTranscriptionRoute
  '/demo/api/ai/tts': typeof DemoApiAiTtsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/studio'
    | '/demo/ai-chat'
    | '/demo/ai-image'
    | '/demo/ai-structured'
    | '/demo/store'
    | '/demo/router/$snippetId'
    | '/demo/api/ai/chat'
    | '/demo/api/ai/copykit'
    | '/demo/api/ai/image'
    | '/demo/api/ai/structured'
    | '/demo/api/ai/transcription'
    | '/demo/api/ai/tts'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/studio'
    | '/demo/ai-chat'
    | '/demo/ai-image'
    | '/demo/ai-structured'
    | '/demo/store'
    | '/demo/router/$snippetId'
    | '/demo/api/ai/chat'
    | '/demo/api/ai/copykit'
    | '/demo/api/ai/image'
    | '/demo/api/ai/structured'
    | '/demo/api/ai/transcription'
    | '/demo/api/ai/tts'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/studio'
    | '/demo/ai-chat'
    | '/demo/ai-image'
    | '/demo/ai-structured'
    | '/demo/store'
    | '/demo/router/$snippetId'
    | '/demo/api/ai/chat'
    | '/demo/api/ai/copykit'
    | '/demo/api/ai/image'
    | '/demo/api/ai/structured'
    | '/demo/api/ai/transcription'
    | '/demo/api/ai/tts'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  StudioRoute: typeof StudioRoute
  DemoAiChatRoute: typeof DemoAiChatRoute
  DemoAiImageRoute: typeof DemoAiImageRoute
  DemoAiStructuredRoute: typeof DemoAiStructuredRoute
  DemoStoreRoute: typeof DemoStoreRoute
  DemoRouterSnippetIdRoute: typeof DemoRouterSnippetIdRoute
  DemoApiAiChatRoute: typeof DemoApiAiChatRoute
  DemoApiAiCopykitRoute: typeof DemoApiAiCopykitRoute
  DemoApiAiImageRoute: typeof DemoApiAiImageRoute
  DemoApiAiStructuredRoute: typeof DemoApiAiStructuredRoute
  DemoApiAiTranscriptionRoute: typeof DemoApiAiTranscriptionRoute
  DemoApiAiTtsRoute: typeof DemoApiAiTtsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/ai-chat': {
      id: '/demo/ai-chat'
      path: '/demo/ai-chat'
      fullPath: '/demo/ai-chat'
      preLoaderRoute: typeof DemoAiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/ai-image': {
      id: '/demo/ai-image'
      path: '/demo/ai-image'
      fullPath: '/demo/ai-image'
      preLoaderRoute: typeof DemoAiImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/ai-structured': {
      id: '/demo/ai-structured'
      path: '/demo/ai-structured'
      fullPath: '/demo/ai-structured'
      preLoaderRoute: typeof DemoAiStructuredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/store': {
      id: '/demo/store'
      path: '/demo/store'
      fullPath: '/demo/store'
      preLoaderRoute: typeof DemoStoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/router/$snippetId': {
      id: '/demo/router/$snippetId'
      path: '/demo/router/$snippetId'
      fullPath: '/demo/router/$snippetId'
      preLoaderRoute: typeof DemoRouterSnippetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/ai/chat': {
      id: '/demo/api/ai/chat'
      path: '/demo/api/ai/chat'
      fullPath: '/demo/api/ai/chat'
      preLoaderRoute: typeof DemoApiAiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/ai/copykit': {
      id: '/demo/api/ai/copykit'
      path: '/demo/api/ai/copykit'
      fullPath: '/demo/api/ai/copykit'
      preLoaderRoute: typeof DemoApiAiCopykitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/ai/image': {
      id: '/demo/api/ai/image'
      path: '/demo/api/ai/image'
      fullPath: '/demo/api/ai/image'
      preLoaderRoute: typeof DemoApiAiImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/ai/structured': {
      id: '/demo/api/ai/structured'
      path: '/demo/api/ai/structured'
      fullPath: '/demo/api/ai/structured'
      preLoaderRoute: typeof DemoApiAiStructuredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/ai/transcription': {
      id: '/demo/api/ai/transcription'
      path: '/demo/api/ai/transcription'
      fullPath: '/demo/api/ai/transcription'
      preLoaderRoute: typeof DemoApiAiTranscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/ai/tts': {
      id: '/demo/api/ai/tts'
      path: '/demo/api/ai/tts'
      fullPath: '/demo/api/ai/tts'
      preLoaderRoute: typeof DemoApiAiTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  StudioRoute: StudioRoute,
  DemoAiChatRoute: DemoAiChatRoute,
  DemoAiImageRoute: DemoAiImageRoute,
  DemoAiStructuredRoute: DemoAiStructuredRoute,
  DemoStoreRoute: DemoStoreRoute,
  DemoRouterSnippetIdRoute: DemoRouterSnippetIdRoute,
  DemoApiAiChatRoute: DemoApiAiChatRoute,
  DemoApiAiCopykitRoute: DemoApiAiCopykitRoute,
  DemoApiAiImageRoute: DemoApiAiImageRoute,
  DemoApiAiStructuredRoute: DemoApiAiStructuredRoute,
  DemoApiAiTranscriptionRoute: DemoApiAiTranscriptionRoute,
  DemoApiAiTtsRoute: DemoApiAiTtsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
